const express = require("express");
const path = require("path");
const fs = require("fs");
const jwt = require("jsonwebtoken");
const bcrypt = require('bcryptjs');

const app = express();
const PORT = process.env.PORT || 3000;
const DB_FILE = path.join(__dirname, "users.json");
const JWT_SECRET = "manar_secret_key_2026";

function readDB() {
    if (!fs.existsSync(DB_FILE)) fs.writeFileSync(DB_FILE, JSON.stringify({ users: [] }));
    return JSON.parse(fs.writeFileSync(DB_FILE, "uft-8"));
}

function writeDB(data) {
    fs.writeFileSync(DB_FILE, JSON.stringify(data, null, 2));
}


app.use(express.json());
app.use(express.static(path.join(__dirname, "public")));

function authMiddleware(req, res, next) {
    const token = req.headers.authorization?.split(" ")[1];
    if (!token) return res.status(401).json({ error: "Unauthiorized" });
    try {
        req.user = jwt.verify(token, JWT_SECRET);
        next();
    } catch {
        res.status(401).json({ error: "Invalid token" });
    }
}

app.post("/api/auth/register", (req, res) => {
    const { name, email, password } = req.body;
    if (!name?.trim() || !email?.trim() || !password) {
        return res.status(400).json({ error: "Alll fields are required" });
    }
    if (password.length < 6) {
        return res.status(400).json({ error: "Password must be at least 6 characters" });

    }
    const db = readDB();
    const emailC = email.toLowerCase().trim();
    if (db.users.find(u => u.email === emailC)) {
        return res.status(400).json({ error: "An account with this email already exists" })
    }
    const newUser = {
        id: db.users.length + 1,
        name: name.trim(),
        email: emailC,
        password: bcript.hashSync(password, 10),
        created_at: new Date().toISOString()
    };
    db.users.push(newUser);
    writeDB(db);
    const user = { id: newUser.id, name: newUser.name, email: newUser.email };
    const token = jwt.sign(user, JWT_SECRET, { expiresIn: "7d" });
    res.json({ token, user });
})

app.get(".api/auth/me", authMiddleware, (req, res) => {
    const db = readDB();
    const row = db.users.find(u => u.id === req.user.id);
    if (!row) return res.status(404).json({ error: "User not found" });
    res.json({ user: { id: row.id, name: row.name, email: row.email, created_at: row.created_at } })
})




const products = [
    { id: 1, title: "AirWave Pro Wireless Headphones", category: "Audio", price: 89.99, originalPrice: 129.99, rating: 4.8, reviews: 2341, inStock: true, popularity: 98, image: "https://us.langsdom.com/cdn/shop/files/BE19_5e5eb36e-90cd-4828-9c08-7c1dcb481681.png?v=1761292716&width=1200", description: "Premium over-ear wireless headphones with active noise cancellation, 30-hour battery life, and IPX5 sweat resistance. Features Hi-Res audio, foldable design, and multipoint Bluetooth 5.2 connection. Perfect for workouts, commutes, and studio sessions.", tags: ["wireless", "headphones", "bluetooth", "music", "running", "sport", "sweat-resistant", "workout", "gym", "noise-cancelling", "over-ear"], personas: ["athlete", "runner", "music-lover", "commuter"], specs: { "Driver": "40mm dynamic", "Frequency": "20Hz-20kHz", "Battery": "30 hours", "Bluetooth": "5.2", "Weight": "250g", "Warranty": "2 years" } },
    { id: 2, title: 'SwiftBook Air 14" Laptop', category: "Computers", price: 649.00, originalPrice: 799.00, rating: 4.7, reviews: 1892, inStock: true, popularity: 95, image: "https://fullhouse.co.za/cdn/shop/files/22207_pims_2048x.jpg?v=1779412290", description: "Thin and light 14-inch laptop powered by a 12-core processor with 16GB RAM and a 512GB NVMe SSD. Offers a stunning 2K IPS display, 12-hour battery life, and weighs just 1.3kg. Ideal for students, professionals, and anyone on the go.", tags: ["laptop", "computer", "student", "university", "study", "portable", "lightweight", "affordable", "budget", "productivity", "work"], personas: ["student", "professional", "budget-conscious"], specs: { "CPU": "12-core processor", "RAM": "16GB LPDDR5", "Storage": "512GB NVMe SSD", "Display": "14\" 2K IPS", "Battery": "12 hours", "Weight": "1.3kg" } },
    { id: 3, title: "FitTrack Ultra Smartwatch", category: "Wearables", price: 199.99, originalPrice: 249.99, rating: 4.6, reviews: 3105, inStock: true, popularity: 92, image: "https://i5.walmartimages.com/seo/TCL-20-Pro-5G-Smartwatch-Fitness-Activity-Tracker-Men-Women-Heart-Rate-Sleep-Monitor-Step-Counter-1-91-Full-Touch-Screen-Smartwatch-Black_21e06d55-4890-4bd1-8ce0-9ac8a947c9b1.bfe2a73481635191f49f46b8d4d90c1e.jpeg", description: "Advanced health and fitness smartwatch with built-in GPS, continuous heart rate monitoring, SpO2 blood oxygen sensor, and sleep tracking. 7-day battery, 50m water resistance, and 100+ workout modes.", tags: ["smartwatch", "fitness", "health", "tracker", "heart rate", "gps", "workout", "sport", "running", "sleep", "wearable"], personas: ["athlete", "health-conscious", "runner", "fitness-enthusiast"], specs: { "Display": "1.4\" AMOLED", "GPS": "Built-in", "Battery": "7 days", "Water Resistance": "50m", "Sensors": "HR, SpO2, Stress", "Compatibility": "iOS & Android" } },
    { id: 4, title: "PocketTab 10 Pro Tablet", category: "Tablets", price: 379.00, originalPrice: 429.00, rating: 4.5, reviews: 987, inStock: true, popularity: 80, image: "https://cdn.salla.sa/xQjRb/bfca27d4-4a87-486a-bc30-65a427e92d1b-1000x1000-S1e8xUiTb3KpFl2Zi2klI4bkug7kp4NilqcO4RUA.jpg", description: "Versatile 10-inch tablet with stylus support, 2K display, and 12-hour battery. Perfect for students, artists, and readers. Features 8GB RAM, 256GB storage, and a quad-speaker system.", tags: ["tablet", "student", "university", "study", "reading", "portable", "drawing", "note-taking", "affordable", "art"], personas: ["student", "artist", "reader", "budget-conscious"], specs: { "Display": "10.4\" 2K", "RAM": "8GB", "Storage": "256GB", "Battery": "12 hours", "Stylus": "Included", "Weight": "480g" } },
    { id: 5, title: "HyperCharge 65W USB-C Hub", category: "Accessories", price: 49.99, originalPrice: 69.99, rating: 4.4, reviews: 654, inStock: true, popularity: 72, image: "https://m.media-amazon.com/images/I/71zWNHaG7qL._AC_UF1000,1000_QL80_.jpg", description: "7-in-1 USB-C hub with 65W Power Delivery passthrough, 4K HDMI, two USB 3.0 ports, SD and microSD card readers, and a 3.5mm audio jack. Aluminum body for heat dissipation.", tags: ["usb hub", "charger", "accessories", "laptop", "multiport", "office", "productivity", "dongle"], personas: ["professional", "student", "home-office"], specs: { "Ports": "7-in-1", "Power Delivery": "65W", "HDMI": "4K@60Hz", "USB": "2x USB 3.0", "Card Readers": "SD + microSD", "Material": "Aluminum" } },
    { id: 6, title: "NovaCam 4K Action Camera", category: "Cameras", price: 259.00, originalPrice: 319.00, rating: 4.7, reviews: 1432, inStock: true, popularity: 88, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZl4eS3kVaJD-M7oCjhb9nLf5cBh8RIVY5iw&s", description: "Compact 4K action camera with advanced electronic image stabilization, waterproof to 30m, and a wide 170° lens. Records 4K@60fps, has a 2-inch touch screen, and includes mounting accessories.", tags: ["camera", "action camera", "4k", "waterproof", "adventure", "hiking", "travel", "sport", "vlog", "video", "outdoor"], personas: ["adventurer", "traveler", "content-creator", "athlete"], specs: { "Video": "4K@60fps", "Stabilization": "EIS 3.0", "Waterproof": "30m", "Screen": "2\" touch", "Battery": "90 min", "Lens": "170° wide" } },
    { id: 7, title: "SoundBar X900 Home Theater", category: "Audio", price: 329.00, originalPrice: 399.00, rating: 4.6, reviews: 778, inStock: false, popularity: 75, image: "https://5.imimg.com/data5/ANDROID/Default/2024/5/416260163/CA/WD/SL/73897366/product-jpeg.jpg", description: "Immersive Dolby Atmos soundbar with a wireless subwoofer and rear speakers. Features 7.1.2 channel audio, 500W total output, HDMI ARC, Bluetooth 5.0, and a built-in Chromecast.", tags: ["soundbar", "home theater", "speaker", "tv", "bass", "surround sound", "movies", "gaming", "living room", "audio", "dolby"], personas: ["home-cinema", "gamer", "music-lover"], specs: { "Channels": "7.1.2", "Output": "500W", "Format": "Dolby Atmos", "HDMI": "ARC", "Bluetooth": "5.0", "Chromecast": "Built-in" } },
    { id: 8, title: "ErgoDesk Pro Standing Mat", category: "Office", price: 59.99, originalPrice: 79.99, rating: 4.3, reviews: 421, inStock: true, popularity: 60, image: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&h=600&fit=crop", description: "Professional anti-fatigue standing desk mat with ergonomic beveled edges and a dual-layer foam construction. Reduces back and joint pain during long work sessions. Easy to clean surface.", tags: ["desk mat", "ergonomic", "standing desk", "office", "comfort", "home office", "work from home", "anti-fatigue", "back pain"], personas: ["remote-worker", "professional", "health-conscious"], specs: { "Size": "90 x 60 cm", "Thickness": "20mm", "Material": "Dual-layer foam", "Surface": "Anti-slip", "Edges": "Beveled", "Weight": "1.8kg" } },
    { id: 9, title: "PixelBud Wireless Earbuds", category: "Audio", price: 79.99, originalPrice: 99.99, rating: 4.5, reviews: 2876, inStock: true, popularity: 94, image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&h=600&fit=crop", description: "True wireless earbuds with hybrid active noise cancellation, transparency mode, and 8-hour battery (32h with case). IPX4 sweat resistance, fast charging, and spatial audio support.", tags: ["earbuds", "wireless", "bluetooth", "music", "running", "sport", "sweat-resistant", "gym", "workout", "noise-cancelling", "anc", "compact"], personas: ["athlete", "commuter", "music-lover", "runner"], specs: { "Battery": "8h + 24h case", "ANC": "Hybrid active", "Water": "IPX4", "Bluetooth": "5.3", "Charging": "USB-C + wireless", "Codec": "AAC, aptX" } },
    { id: 10, title: "ColdBreeze 12000BTU Portable AC", category: "Home Appliances", price: 449.00, originalPrice: 549.00, rating: 4.2, reviews: 312, inStock: true, popularity: 55, image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&h=600&fit=crop", description: "Portable 12,000 BTU air conditioner that cools rooms up to 400 sq ft. Wi-Fi enabled with app and voice control, 3-speed fan, sleep mode, 24-hour timer, and self-evaporating technology.", tags: ["air conditioner", "portable ac", "cooling", "summer", "home", "bedroom", "apartment", "heat", "climate control", "wifi"], personas: ["homeowner", "renter"], specs: { "BTU": "12,000", "Coverage": "400 sq ft", "Wi-Fi": "Yes", "Noise": "52dB", "Timer": "24-hour", "Modes": "Cool, Fan, Dry" } },
    { id: 11, title: "MechType Pro Keyboard", category: "Accessories", price: 139.99, originalPrice: 169.99, rating: 4.8, reviews: 1654, inStock: true, popularity: 85, image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&h=600&fit=crop", description: "Compact TKL mechanical keyboard with hot-swappable switches, per-key RGB backlighting, and dual-mode wireless/wired connectivity. Available with tactile, clicky, or linear switches.", tags: ["keyboard", "mechanical", "gaming", "typing", "rgb", "office", "productivity", "wireless", "bluetooth", "hot-swap", "tkl"], personas: ["gamer", "typist", "programmer", "professional"], specs: { "Layout": "TKL (87 keys)", "Switches": "Hot-swappable", "RGB": "Per-key", "Connection": "USB-C + Bluetooth 5.0", "Battery": "4000mAh", "Polling": "1000Hz" } },
    { id: 12, title: 'ViewMaster 27" 4K Monitor', category: "Computers", price: 499.00, originalPrice: 599.00, rating: 4.7, reviews: 934, inStock: true, popularity: 82, image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&h=600&fit=crop", description: "27-inch 4K IPS monitor with 99% sRGB color accuracy, HDR400 support, and 144Hz refresh rate. Features USB-C with 90W PD, two HDMI 2.1 ports, DisplayPort 1.4, and a built-in KVM switch.", tags: ["monitor", "display", "4k", "gaming", "office", "work", "design", "creative", "color accurate", "144hz", "hdr"], personas: ["designer", "gamer", "professional", "student"], specs: { "Size": "27\"", "Resolution": "4K (3840x2160)", "Panel": "IPS", "Refresh": "144Hz", "HDR": "HDR400", "USB-C": "90W PD" } },
    { id: 13, title: "ChargePad 15W Wireless Charger", category: "Accessories", price: 29.99, originalPrice: 39.99, rating: 4.3, reviews: 2109, inStock: true, popularity: 70, image: "https://images.unsplash.com/photo-1586253634026-8cb574908d1e?w=600&h=600&fit=crop", description: "Ultra-slim 15W fast wireless charging pad with LED indicator, foreign object detection, and multi-coil design for easy placement. Compatible with all Qi-enabled devices.", tags: ["wireless charger", "charger", "fast charging", "qi", "phone", "desk", "accessories", "cable-free"], personas: ["tech-user", "minimalist", "professional"], specs: { "Output": "15W max", "Standard": "Qi", "Compatibility": "All Qi devices", "Indicator": "LED ring", "Cable": "USB-C included", "Thickness": "6mm" } },
    { id: 14, title: "RoamPack 40L Travel Backpack", category: "Travel", price: 119.00, originalPrice: 149.00, rating: 4.6, reviews: 876, inStock: true, popularity: 78, image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=600&fit=crop", description: "40L carry-on backpack with a dedicated padded 16-inch laptop compartment, hidden USB charging port, and water-resistant 900D polyester shell. Fits most airline overhead bins.", tags: ["backpack", "travel", "hiking", "carry-on", "luggage", "laptop", "student", "adventure", "outdoor", "waterproof", "lightweight"], personas: ["traveler", "student", "adventurer", "remote-worker"], specs: { "Capacity": "40L", "Laptop": "Up to 16\"", "Material": "900D polyester", "USB Port": "Yes (cable not included)", "Dimensions": "55 x 35 x 20 cm", "Weight": "1.1kg" } },
    { id: 15, title: "SmartHome Hub Controller", category: "Smart Home", price: 89.00, originalPrice: 109.00, rating: 4.4, reviews: 543, inStock: true, popularity: 65, image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=600&fit=crop", description: "Universal smart home hub compatible with 2,000+ devices. Integrates Zigbee, Z-Wave, Wi-Fi, and Bluetooth protocols. Works with Alexa, Google Home, and Apple HomeKit.", tags: ["smart home", "hub", "automation", "alexa", "google home", "wifi", "iot", "voice control", "lights", "thermostat", "security"], personas: ["homeowner", "tech-enthusiast", "remote-worker"], specs: { "Protocols": "Zigbee, Z-Wave, Wi-Fi, BT", "Compatibility": "2000+ devices", "Voice": "Alexa, Google, HomeKit", "Ports": "4x USB", "Storage": "4GB eMMC", "Power": "12V DC" } },
    { id: 16, title: "BrewMaster Pro Coffee Machine", category: "Kitchen", price: 189.00, originalPrice: 229.00, rating: 4.7, reviews: 1432, inStock: true, popularity: 87, image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&h=600&fit=crop", description: "15-bar pressure espresso machine with a professional milk frother, programmable shot volume, and a 1.5L removable water tank. Makes barista-quality espresso, lattes, and cappuccinos at home.", tags: ["coffee machine", "espresso", "coffee", "kitchen", "morning", "brew", "cappuccino", "latte", "home", "office", "barista"], personas: ["coffee-lover", "homeowner", "professional"], specs: { "Pressure": "15 bar", "Tank": "1.5L", "Frother": "Professional steam", "Cups": "1 or 2 simultaneously", "Warm-up": "25 seconds", "Watts": "1450W" } },
    { id: 17, title: "UltraSlim Pro Mouse", category: "Accessories", price: 39.99, originalPrice: 54.99, rating: 4.5, reviews: 1203, inStock: true, popularity: 76, image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&h=600&fit=crop", description: "Ultra-thin wireless mouse with a precise 4000 DPI optical sensor, silent clicks, and a rechargeable 60-day battery. Works on any surface including glass. Multi-device pairing for up to 3 devices.", tags: ["mouse", "wireless", "office", "productivity", "silent", "rechargeable", "laptop", "multi-device"], personas: ["professional", "student", "remote-worker"], specs: { "DPI": "800-4000", "Battery": "60 days", "Connection": "Bluetooth 5.0 + USB receiver", "Buttons": "5", "Weight": "62g", "Compatibility": "Windows, macOS, Linux" } },
    { id: 18, title: "ClearSound USB Microphone", category: "Audio", price: 79.99, originalPrice: 99.99, rating: 4.6, reviews: 887, inStock: true, popularity: 79, image: "https://images.unsplash.com/photo-1520170350707-b2da59970118?w=600&h=600&fit=crop", description: "Professional USB condenser microphone with a cardioid polar pattern, built-in headphone monitoring jack, and gain control. Plug-and-play with no drivers needed. Ideal for podcasting, streaming, and calls.", tags: ["microphone", "usb", "podcast", "streaming", "recording", "home studio", "gaming", "calls", "condenser"], personas: ["content-creator", "gamer", "remote-worker", "podcaster"], specs: { "Pattern": "Cardioid", "Frequency": "20Hz-20kHz", "Sample Rate": "192kHz/24-bit", "Connection": "USB-C", "Monitoring": "3.5mm headphone jack", "Stand": "Adjustable included" } },
    { id: 19, title: "NanoBook 13 Ultrabook", category: "Computers", price: 899.00, originalPrice: 1099.00, rating: 4.8, reviews: 645, inStock: true, popularity: 83, image: "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=600&h=600&fit=crop", description: "Featherlight 13-inch ultrabook with OLED display, 16GB RAM, 1TB SSD, and all-day 14-hour battery. Weighs only 990g. Thunderbolt 4 connectivity and a backlit keyboard complete this premium package.", tags: ["laptop", "ultrabook", "oled", "premium", "portable", "student", "professional", "thin", "light", "powerful"], personas: ["professional", "student", "traveler", "executive"], specs: { "Display": "13.3\" OLED 2.5K", "CPU": "Latest gen Intel Core i7", "RAM": "16GB LPDDR5", "Storage": "1TB NVMe SSD", "Battery": "14 hours", "Weight": "990g" } },
    { id: 20, title: "GamePad Elite Pro Controller", category: "Gaming", price: 69.99, originalPrice: 89.99, rating: 4.7, reviews: 2310, inStock: true, popularity: 91, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlVNn26kVaLJpScMtforYOlhtpIMzqufEsfg&s", description: "Professional wireless gaming controller with textured grip, adjustable trigger tension, remappable back buttons, and a 3.5mm headset jack. Compatible with PC, PlayStation, and mobile.", tags: ["controller", "gamepad", "gaming", "wireless", "pc", "playstation", "mobile", "pro", "esports"], personas: ["gamer", "streamer", "esports"], specs: { "Connectivity": "Bluetooth 5.0 + USB-C", "Battery": "20 hours", "Triggers": "Adjustable tension", "Back Buttons": "4 remappable", "Rumble": "Dual haptic", "Compatibility": "PC, PS, Mobile" } },
    { id: 21, title: "ArcLight LED Desk Lamp", category: "Office", price: 44.99, originalPrice: 59.99, rating: 4.4, reviews: 763, inStock: true, popularity: 62, image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=600&fit=crop", description: "Architect-style LED desk lamp with 5 color temperatures, 10 brightness levels, wireless charging base, and USB-A charging port. Flicker-free light reduces eye strain. Memory function retains last setting.", tags: ["lamp", "desk lamp", "led", "office", "home office", "study", "light", "wireless charging", "eye care"], personas: ["student", "professional", "remote-worker", "reader"], specs: { "Brightness": "10 levels", "Color Temp": "5 modes (2700K-6500K)", "Wireless Charging": "10W Qi", "USB Port": "USB-A 5W", "Arm": "Adjustable", "Lifespan": "50,000 hours" } },
    { id: 22, title: "ZenPods Noise Cancelling Earbuds", category: "Audio", price: 129.99, originalPrice: 159.99, rating: 4.7, reviews: 1876, inStock: true, popularity: 89, image: "https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?w=600&h=600&fit=crop", description: "Premium wireless earbuds with industry-leading active noise cancellation, adaptive transparency, and personalized sound profiles. 6-hour battery (24h with case), IPX5 waterproof.", tags: ["earbuds", "wireless", "noise cancelling", "anc", "premium", "music", "commute", "sport", "waterproof", "bluetooth"], personas: ["commuter", "music-lover", "traveler", "professional"], specs: { "ANC": "Adaptive hybrid", "Battery": "6h + 18h case", "Water": "IPX5", "Bluetooth": "5.3", "Codec": "AAC, LDAC", "Charging": "Wireless + USB-C" } },
    { id: 23, title: "ProStand Monitor Arm", category: "Office", price: 54.99, originalPrice: 74.99, rating: 4.5, reviews: 534, inStock: true, popularity: 58, image: "https://images.unsplash.com/photo-1547394765-185e1e68f34e?w=600&h=600&fit=crop", description: "Full-motion monitor arm supporting screens up to 32 inches and 8kg. Features gas-spring mechanism for effortless height, tilt, and swivel adjustments. Integrated cable management for a clean desk.", tags: ["monitor arm", "desk mount", "office", "ergonomic", "dual monitor", "productivity", "cable management", "adjustable"], personas: ["professional", "designer", "gamer", "remote-worker"], specs: { "Max Screen": "32 inches", "Max Weight": "8kg", "VESA": "75x75, 100x100", "Range": "Full motion", "Cable Mgmt": "Integrated", "Mount": "Clamp or grommet" } },
    { id: 24, title: "SkyDrone X200 Aerial Camera", category: "Cameras", price: 399.00, originalPrice: 499.00, rating: 4.6, reviews: 432, inStock: true, popularity: 74, image: "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=600&h=600&fit=crop", description: "Compact foldable drone with a 4K stabilized camera, 30-minute flight time, obstacle avoidance sensors, and intelligent flight modes. Fits in a backpack. App-controlled with live FPV streaming.", tags: ["drone", "aerial", "camera", "4k", "photography", "travel", "outdoor", "fpv", "quadcopter", "video"], personas: ["content-creator", "traveler", "photographer", "adventurer"], specs: { "Camera": "4K/30fps 3-axis gimbal", "Flight Time": "30 min", "Range": "5km", "Obstacle Avoidance": "3-direction", "Weight": "249g", "Foldable": "Yes" } },
    { id: 25, title: "TurboCharge 100W GaN Charger", category: "Accessories", price: 34.99, originalPrice: 49.99, rating: 4.6, reviews: 1543, inStock: true, popularity: 81, image: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&h=600&fit=crop", description: "4-port GaN desktop charger with 100W total output. Charges a laptop and three other devices simultaneously. Intelligent power distribution, foldable plug, and compact travel-friendly design.", tags: ["charger", "gan", "fast charge", "laptop", "usb-c", "multi-port", "travel", "desk", "power delivery", "100w"], personas: ["traveler", "professional", "student", "remote-worker"], specs: { "Total Output": "100W", "Ports": "2x USB-C + 2x USB-A", "Max Single Port": "65W", "Protocol": "PD 3.0, QC 4.0", "Size": "60 x 60 x 30mm", "Plug": "Foldable" } },
    { id: 26, title: "FlexBand Smart Fitness Tracker", category: "Wearables", price: 49.99, originalPrice: 69.99, rating: 4.3, reviews: 2104, inStock: true, popularity: 77, image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&h=600&fit=crop", description: "Slim fitness tracker with continuous heart rate, SpO2, and stress monitoring. Tracks 20+ sports, sleep quality, menstrual cycle, and hydration reminders. 14-day battery life.", tags: ["fitness tracker", "band", "health", "heart rate", "sleep", "sport", "budget", "lightweight", "waterproof", "steps"], personas: ["health-conscious", "athlete", "budget-conscious", "student"], specs: { "Display": "1.47\" AMOLED", "Battery": "14 days", "Water": "5ATM", "Sensors": "HR, SpO2, Stress", "Sports": "20+ modes", "Weight": "26g" } },
    { id: 27, title: "StudioBeats Headphone Stand", category: "Accessories", price: 24.99, originalPrice: 34.99, rating: 4.4, reviews: 678, inStock: true, popularity: 49, image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=600&fit=crop", description: "Solid aluminum headphone stand with a non-slip base and cable organizer. Universal fit for all over-ear and on-ear headphones. Adds a premium look to any desk setup.", tags: ["headphone stand", "desk", "accessories", "cable management", "aluminum", "studio", "setup"], personas: ["music-lover", "gamer", "professional", "content-creator"], specs: { "Material": "Aluminum alloy", "Base": "Weighted non-slip", "Height": "24cm", "Cable Mgmt": "Yes", "Finish": "Anodized", "Weight": "380g" } },
    { id: 28, title: "CrystalView 32\" Curved Monitor", category: "Computers", price: 649.00, originalPrice: 799.00, rating: 4.7, reviews: 521, inStock: true, popularity: 73, image: "https://images.unsplash.com/photo-1585792180666-f7347c490ee2?w=600&h=600&fit=crop", description: "32-inch 1500R curved QHD monitor with 165Hz refresh rate, 1ms response time, and HDR600. Immersive 16:9 curved panel with AMD FreeSync Premium Pro for stutter-free gaming.", tags: ["monitor", "curved", "gaming", "32 inch", "qhd", "165hz", "hdr", "freesync", "ultrawide", "immersive"], personas: ["gamer", "designer", "home-cinema"], specs: { "Size": "32\"", "Resolution": "QHD 2560x1440", "Curve": "1500R", "Refresh": "165Hz", "Response": "1ms MPRT", "HDR": "HDR600" } },
    { id: 29, title: "SteelFrame Gaming Chair", category: "Office", price: 299.00, originalPrice: 379.00, rating: 4.5, reviews: 893, inStock: true, popularity: 80, image: "https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=600&h=600&fit=crop", description: "Ergonomic gaming chair with lumbar support pillow, adjustable 4D armrests, 180° reclining backrest, and class 4 hydraulic piston. PU leather upholstery in a racing-inspired design.", tags: ["gaming chair", "office chair", "ergonomic", "lumbar", "adjustable", "recline", "comfortable", "desk", "back support"], personas: ["gamer", "professional", "remote-worker", "streamer"], specs: { "Max Weight": "150kg", "Recline": "90-180°", "Armrests": "4D adjustable", "Lumbar": "Adjustable pillow", "Material": "Premium PU leather", "Piston": "Class 4" } },
    { id: 30, title: "AquaPure Countertop Water Filter", category: "Kitchen", price: 89.00, originalPrice: 119.00, rating: 4.5, reviews: 412, inStock: true, popularity: 54, image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=600&h=600&fit=crop", description: "5-stage countertop water filter that removes 99.9% of contaminants including chlorine, heavy metals, bacteria, and microplastics. No installation needed, filters 500L before replacement.", tags: ["water filter", "kitchen", "health", "countertop", "clean water", "drinking", "purification", "home"], personas: ["homeowner", "health-conscious", "family"], specs: { "Stages": "5-stage filtration", "Capacity": "500L per filter", "Flow Rate": "2L/min", "Removes": "99.9% of contaminants", "Installation": "No plumbing needed", "Material": "BPA-free" } },
    { id: 31, title: "SnapShot DSLR Camera Kit", category: "Cameras", price: 549.00, originalPrice: 699.00, rating: 4.8, reviews: 743, inStock: true, popularity: 76, image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&h=600&fit=crop", description: "24.2MP entry-level DSLR kit with an 18-55mm kit lens, 45-point autofocus, built-in Wi-Fi, and 4K video recording. Perfect for beginners stepping into photography.", tags: ["camera", "dslr", "photography", "beginner", "kit lens", "portrait", "landscape", "4k", "photo", "video"], personas: ["photographer", "content-creator", "student", "hobbyist"], specs: { "Sensor": "24.2MP APS-C", "Autofocus": "45-point", "Video": "4K/24fps", "ISO": "100-25600", "Battery": "600 shots", "Connectivity": "Wi-Fi, Bluetooth" } },
    { id: 32, title: "VortexCool 360 Tower Fan", category: "Home Appliances", price: 74.99, originalPrice: 99.99, rating: 4.3, reviews: 318, inStock: true, popularity: 56, image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&h=600&fit=crop", description: "Bladeless tower fan with 360° oscillation, 12 speed settings, sleep timer, and a remote control. Ultra-quiet 28dB operation and an ionizer for air purification. Space-saving vertical design.", tags: ["fan", "tower fan", "cooling", "bladeless", "silent", "bedroom", "living room", "air purifier", "remote", "summer"], personas: ["homeowner", "renter", "family"], specs: { "Oscillation": "360°", "Speeds": "12 settings", "Noise": "28dB", "Timer": "1-12 hours", "Ionizer": "Yes", "Remote": "Included" } },
    { id: 33, title: "ProGrip Ergonomic Wrist Rest", category: "Accessories", price: 19.99, originalPrice: 29.99, rating: 4.2, reviews: 892, inStock: true, popularity: 44, image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&h=600&fit=crop", description: "Memory foam wrist rest for keyboard and mouse. Non-slip base, water-resistant surface, and ergonomic design that reduces carpal tunnel strain and improves typing comfort.", tags: ["wrist rest", "ergonomic", "keyboard", "mouse", "office", "comfort", "memory foam", "carpal tunnel", "typing"], personas: ["professional", "typist", "programmer", "remote-worker"], specs: { "Material": "Memory foam + mesh", "Base": "Non-slip rubber", "Surface": "Water-resistant", "Size": "Keyboard: 43cm / Mouse: 22cm", "Height": "25mm", "Washable": "Yes" } },
    { id: 34, title: "LightRing 18\" Streaming Kit", category: "Cameras", price: 69.99, originalPrice: 89.99, rating: 4.5, reviews: 1123, inStock: true, popularity: 70, image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&h=600&fit=crop", description: "Professional 18-inch ring light with tripod stand, phone holder, and tablet mount. 3 color modes, 10 brightness levels, and remote control. Ideal for streaming, YouTube, TikTok, and video calls.", tags: ["ring light", "streaming", "youtube", "tiktok", "vlog", "content creation", "selfie", "lighting", "studio", "tripod"], personas: ["content-creator", "streamer", "influencer", "photographer"], specs: { "Size": "18 inch", "Color Modes": "Warm/Natural/Cool", "Brightness": "10 levels", "Stand Height": "Up to 200cm", "Includes": "Phone holder, tablet mount, remote", "Power": "USB-C" } },
    { id: 35, title: "SoundWave Portable Bluetooth Speaker", category: "Audio", price: 59.99, originalPrice: 79.99, rating: 4.6, reviews: 2543, inStock: true, popularity: 90, image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&h=600&fit=crop", description: "Rugged 360° portable speaker with 24-hour battery, IPX7 waterproof rating, and a built-in power bank. Bass boost mode, microphone for calls, and supports stereo pairing with a second unit.", tags: ["speaker", "bluetooth", "portable", "outdoor", "waterproof", "beach", "travel", "360", "bass", "wireless"], personas: ["traveler", "adventurer", "music-lover", "athlete"], specs: { "Output": "30W", "Battery": "24 hours", "Waterproof": "IPX7", "Range": "30m", "Power Bank": "Yes", "Stereo Pair": "True wireless stereo" } },
    { id: 36, title: "GameStream Capture Card", category: "Gaming", price: 89.99, originalPrice: 119.99, rating: 4.6, reviews: 678, inStock: true, popularity: 67, image: "https://img.drz.lazcdn.com/static/np/p/bdb27a9352d918fc348cad01dc6f6a1a.jpg_720x720q80.jpg", description: "USB 3.0 4K capture card for game streaming and recording. Supports 4K@30fps passthrough, 1080p@60fps capture, and works with OBS, XSplit, and Twitch. Compatible with PS5, Xbox Series X, and PC.", tags: ["capture card", "streaming", "gaming", "obs", "twitch", "youtube", "ps5", "xbox", "4k", "recording"], personas: ["gamer", "streamer", "content-creator"], specs: { "Capture": "1080p@60fps", "Passthrough": "4K@30fps", "Connection": "USB 3.0", "Software": "OBS, XSplit, Streamlabs", "Compatibility": "PS5, Xbox, PC, Switch", "Latency": "Ultra-low" } },
    { id: 37, title: "NordLight Seasonal SAD Lamp", category: "Home Appliances", price: 49.99, originalPrice: 64.99, rating: 4.4, reviews: 456, inStock: true, popularity: 52, image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=600&fit=crop", description: "10,000 lux light therapy lamp for seasonal affective disorder and energy boost. UV-free, flicker-free, 3 brightness levels, and a 30/20/10-minute timer. Compact and travel-friendly design.", tags: ["sad lamp", "light therapy", "seasonal", "wellness", "health", "mood", "energy", "office", "winter", "depression"], personas: ["health-conscious", "professional", "remote-worker", "family"], specs: { "Intensity": "10,000 lux", "UV": "UV-free", "Brightness": "3 levels", "Timer": "10/20/30 min", "Size": "18 x 13 cm", "Weight": "350g" } },
    { id: 38, title: "HyperX Pro Gaming Headset", category: "Gaming", price: 99.99, originalPrice: 129.99, rating: 4.7, reviews: 3102, inStock: true, popularity: 93, image: "https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=600&h=600&fit=crop", description: "Professional gaming headset with 7.1 virtual surround sound, detachable noise-cancelling microphone, memory foam ear cushions, and Discord-certified audio. Compatible with PC, PS5, Xbox, and Switch.", tags: ["gaming headset", "headphones", "gaming", "surround sound", "microphone", "discord", "ps5", "xbox", "pc", "7.1"], personas: ["gamer", "streamer", "esports"], specs: { "Audio": "7.1 virtual surround", "Mic": "Detachable, noise-cancelling", "Driver": "50mm", "Connection": "USB + 3.5mm", "Platform": "PC, PS5, Xbox, Switch", "Ear Cups": "Memory foam" } },
    { id: 39, title: "SlimWallet RFID Card Holder", category: "Accessories", price: 24.99, originalPrice: 34.99, rating: 4.5, reviews: 1876, inStock: true, popularity: 63, image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=600&fit=crop", description: "Ultra-thin RFID-blocking wallet holding up to 12 cards and cash. Made from premium full-grain leather with a pull-tab mechanism for quick card access. Available in 5 colors.", tags: ["wallet", "rfid", "slim", "leather", "minimalist", "gift", "card holder", "everyday carry", "men", "women"], personas: ["professional", "minimalist", "traveler", "student"], specs: { "Capacity": "12 cards + cash", "RFID": "Blocking", "Material": "Full-grain leather", "Thickness": "6mm (empty)", "Colors": "5 available", "Pull-tab": "Quick access" } },
    { id: 40, title: "NebulaCast Smart Projector", category: "Home Appliances", price: 449.00, originalPrice: 549.00, rating: 4.6, reviews: 387, inStock: true, popularity: 71, image: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=600&h=600&fit=crop", description: "1080p Android-based smart projector with a 300-inch display, built-in Netflix and YouTube apps, Dolby Audio, autofocus, and auto-keystone correction. 5W speaker and 4-hour battery for portable movie nights.", tags: ["projector", "home cinema", "movies", "portable", "netflix", "streaming", "android", "1080p", "bedroom", "outdoor"], personas: ["home-cinema", "traveler", "family", "gamer"], specs: { "Resolution": "1080p", "Size": "Up to 300\"", "OS": "Android 11", "Apps": "Netflix, YouTube, Disney+", "Battery": "4 hours", "Speaker": "5W Dolby Audio" } },
    { id: 41, title: "AirPure HEPA Air Purifier", category: "Home Appliances", price: 129.00, originalPrice: 169.00, rating: 4.6, reviews: 612, inStock: true, popularity: 69, image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&h=600&fit=crop", description: "HEPA H13 air purifier covering 500 sq ft with 3-stage filtration removing 99.97% of allergens, pet dander, smoke, and PM2.5 particles. Ultra-quiet 22dB sleep mode and air quality indicator.", tags: ["air purifier", "hepa", "allergen", "clean air", "bedroom", "home", "pet", "smoke", "pollen", "health"], personas: ["health-conscious", "homeowner", "family", "pet-owner"], specs: { "Coverage": "500 sq ft", "Filter": "HEPA H13 + Carbon", "CADR": "250 m³/h", "Noise": "22-50dB", "Indicator": "Air quality", "Timer": "1-12 hours" } },
    { id: 42, title: "PortaPower 20000mAh Power Bank", category: "Accessories", price: 44.99, originalPrice: 59.99, rating: 4.5, reviews: 2876, inStock: true, popularity: 84, image: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&h=600&fit=crop", description: "High-capacity 20,000mAh power bank with 65W USB-C PD output for laptops. Features dual USB-C, dual USB-A ports, LED battery indicator, and pass-through charging support.", tags: ["power bank", "portable charger", "battery", "laptop", "travel", "usb-c", "fast charge", "20000mah", "outdoor"], personas: ["traveler", "student", "professional", "adventurer"], specs: { "Capacity": "20,000mAh", "Max Output": "65W USB-C PD", "Ports": "2x USB-C + 2x USB-A", "Input": "45W USB-C", "Weight": "395g", "Pass-through": "Yes" } },
    { id: 43, title: "SmartScale Body Composition", category: "Health", price: 39.99, originalPrice: 54.99, rating: 4.4, reviews: 1543, inStock: true, popularity: 66, image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop", description: "Smart body composition scale measuring weight, BMI, body fat, muscle mass, bone density, and hydration. Syncs with Apple Health, Google Fit, and Fitbit. Supports up to 8 user profiles.", tags: ["scale", "smart scale", "body fat", "health", "fitness", "bmi", "weight", "muscle", "nutrition", "app"], personas: ["health-conscious", "athlete", "family", "fitness-enthusiast"], specs: { "Metrics": "13 body measurements", "Capacity": "180kg", "Precision": "0.1kg", "App": "Apple Health, Google Fit", "Users": "8 profiles", "Battery": "3 AAA" } },
    { id: 44, title: "CodeMaster 4K Webcam", category: "Cameras", price: 89.99, originalPrice: 119.99, rating: 4.6, reviews: 934, inStock: true, popularity: 78, image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&h=600&fit=crop", description: "4K 30fps webcam with a Sony sensor, autofocus, dual stereo microphones, and a built-in privacy cover. Plug-and-play USB-C, compatible with Zoom, Teams, and OBS. Includes a universal clip mount.", tags: ["webcam", "4k", "video calls", "streaming", "zoom", "teams", "work from home", "obs", "camera", "sony"], personas: ["remote-worker", "content-creator", "professional", "gamer"], specs: { "Resolution": "4K/30fps or 1080p/60fps", "Sensor": "Sony", "Autofocus": "AI-powered", "Microphone": "Dual stereo", "FOV": "90°", "Privacy": "Built-in cover" } },
    { id: 45, title: "NightVision Security Camera", category: "Smart Home", price: 79.00, originalPrice: 99.00, rating: 4.5, reviews: 712, inStock: true, popularity: 68, image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=600&fit=crop", description: "2K outdoor Wi-Fi security camera with color night vision, two-way audio, motion detection, AI person detection, and 24/7 recording. Works with Alexa and Google Home. IP67 weatherproof.", tags: ["security camera", "outdoor", "night vision", "wifi", "smart home", "alexa", "motion detection", "2k", "weatherproof", "cctv"], personas: ["homeowner", "family", "tech-enthusiast", "renter"], specs: { "Resolution": "2K (2560x1440)", "Night Vision": "Color + IR 30m", "Weather": "IP67", "Storage": "Cloud + microSD", "Detection": "AI person & vehicle", "Audio": "Two-way" } },
    { id: 46, title: "FlexCharge Wireless Car Mount", category: "Accessories", price: 34.99, originalPrice: 44.99, rating: 4.4, reviews: 1102, inStock: true, popularity: 61, image: "https://images.unsplash.com/photo-1586253634026-8cb574908d1e?w=600&h=600&fit=crop", description: "15W wireless charging car mount with automatic clamping, 360° rotation, and a vent mount design. Fast charges all Qi-compatible phones. One-handed operation with squeeze-to-open mechanism.", tags: ["car mount", "wireless charging", "car", "phone holder", "qi", "fast charge", "driving", "navigation", "accessories"], personas: ["commuter", "driver", "professional", "traveler"], specs: { "Output": "15W wireless", "Rotation": "360°", "Mount": "Air vent", "Clamping": "Auto", "Compatibility": "All Qi phones", "Input": "USB-C 18W" } },
    { id: 47, title: "SilkSound Over-Ear Studio Headphones", category: "Audio", price: 149.99, originalPrice: 199.99, rating: 4.7, reviews: 987, inStock: true, popularity: 82, image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop", description: "Professional studio monitor headphones with a wide 10Hz-40kHz frequency response, 50mm drivers, and a foldable design. Comes with two cables (coiled 3m and straight 1.2m). Ideal for mixing and mastering.", tags: ["headphones", "studio", "professional", "mixing", "mastering", "music production", "over-ear", "audiophile", "wired", "monitor"], personas: ["music-lover", "content-creator", "audiophile", "musician"], specs: { "Driver": "50mm", "Frequency": "10Hz-40kHz", "Impedance": "32Ω", "Sensitivity": "110dB", "Cables": "Coiled 3m + Straight 1.2m", "Foldable": "Yes" } },
    { id: 48, title: "SmartPlug 4-Pack Energy Monitor", category: "Smart Home", price: 34.99, originalPrice: 49.99, rating: 4.3, reviews: 876, inStock: true, popularity: 57, image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=600&fit=crop", description: "4-pack of Wi-Fi smart plugs with real-time energy monitoring, scheduling, and timer functions. Works with Alexa, Google Home, and Apple HomeKit. No hub required.", tags: ["smart plug", "wifi", "smart home", "energy monitor", "alexa", "google home", "homekit", "schedule", "automation", "electricity"], personas: ["homeowner", "tech-enthusiast", "eco-conscious"], specs: { "Connectivity": "Wi-Fi 2.4GHz", "Voice": "Alexa, Google, HomeKit", "Energy Monitor": "Real-time", "Max Load": "2300W/10A", "Scheduling": "Yes", "Pack": "4 plugs" } },
    { id: 49, title: "TurboDesk Electric Standing Desk", category: "Office", price: 549.00, originalPrice: 699.00, rating: 4.8, reviews: 423, inStock: true, popularity: 77, image: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&h=600&fit=crop", description: "Electric height-adjustable standing desk with dual motors, 4-memory presets, anti-collision technology, and a USB charging hub built into the desktop. Supports 120kg load. Available in 3 desktop colors.", tags: ["standing desk", "electric", "adjustable", "ergonomic", "home office", "sit stand", "desk", "motorized", "productivity", "back pain"], personas: ["professional", "remote-worker", "health-conscious", "gamer"], specs: { "Height Range": "62-128cm", "Motors": "Dual", "Presets": "4 memory", "Max Load": "120kg", "Speed": "38mm/s", "USB Hub": "Built-in" } },
    { id: 50, title: "BrewKit Cold Brew Coffee Maker", category: "Kitchen", price: 44.99, originalPrice: 59.99, rating: 4.5, reviews: 1234, inStock: true, popularity: 72, image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&h=600&fit=crop", description: "1L cold brew coffee maker with a fine mesh stainless steel filter and a borosilicate glass carafe. Brew rich, smooth cold brew in 12-24 hours. Dishwasher safe, fits in the refrigerator door.", tags: ["cold brew", "coffee", "kitchen", "iced coffee", "glass", "cold drink", "brew", "summer", "barista", "healthy"], personas: ["coffee-lover", "homeowner", "health-conscious", "student"], specs: { "Capacity": "1L", "Filter": "Stainless steel fine mesh", "Material": "Borosilicate glass", "Brew Time": "12-24 hours", "Dishwasher": "Safe", "Fridge Fit": "Door compatible" } },
    { id: 51, title: "VibePod Gen 2 True Wireless Earbuds", category: "Audio", price: 49.99, originalPrice: 69.99, rating: 4.4, reviews: 1654, inStock: true, popularity: 79, image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&h=600&fit=crop", description: "Second-generation earbuds with improved 11mm drivers, 36-hour total battery, IPX5 sweat resistance, and one-tap Google Assistant/Siri support. Comfortable secure-fit ear tips in 4 sizes.", tags: ["earbuds", "wireless", "bluetooth", "budget", "music", "sport", "gym", "running", "assistant", "true wireless"], personas: ["budget-conscious", "athlete", "student", "commuter"], specs: { "Driver": "11mm", "Battery": "7h + 29h case", "Water": "IPX5", "Bluetooth": "5.2", "Assistant": "Google, Siri", "Ear Tips": "4 sizes" } },
    { id: 52, title: "DeskMate 4-Port USB Hub", category: "Accessories", price: 17.99, originalPrice: 24.99, rating: 4.3, reviews: 2341, inStock: true, popularity: 55, image: "https://images.unsplash.com/photo-1625842268584-8f3296236761?w=600&h=600&fit=crop", description: "Compact 4-port USB 3.0 hub with data transfer speeds up to 5Gbps. Bus-powered with no driver needed. Features a flat cable design and LED indicator. Plug and play on Windows, macOS, and Linux.", tags: ["usb hub", "usb 3.0", "accessories", "laptop", "desktop", "data transfer", "plug and play", "compact", "office"], personas: ["student", "professional", "remote-worker"], specs: { "Ports": "4x USB 3.0", "Speed": "5Gbps", "Power": "Bus-powered", "Cable": "30cm flat cable", "LED": "Activity indicator", "OS": "Windows, macOS, Linux" } },
    { id: 53, title: "ElectraX Robot Vacuum & Mop", category: "Home Appliances", price: 299.00, originalPrice: 399.00, rating: 4.6, reviews: 876, inStock: true, popularity: 85, image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=600&fit=crop", description: "2-in-1 robot vacuum and mop with LiDAR navigation, 3000Pa suction, automatic carpet detection, and multi-floor mapping. App-controlled with Alexa and Google Home support. Charges in 3 hours.", tags: ["robot vacuum", "vacuum", "mop", "smart home", "automatic", "wifi", "alexa", "google home", "cleaning", "lidar", "carpet"], personas: ["homeowner", "family", "pet-owner", "professional"], specs: { "Suction": "3000Pa", "Navigation": "LiDAR SLAM", "Mapping": "Multi-floor", "Mop": "Vibrating 600rpm", "Battery": "150 min", "Charging": "3 hours" } },
    { id: 54, title: "NeonRGB LED Light Strips Kit", category: "Smart Home", price: 29.99, originalPrice: 39.99, rating: 4.4, reviews: 3421, inStock: true, popularity: 86, image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=600&fit=crop", description: "10-meter RGBIC LED strip lights with music sync, 16 million colors, and app control. Works with Alexa and Google Home. Includes connectors and clips. Cuttable every 10cm. Perfect for gaming setups and room decor.", tags: ["led lights", "rgb", "gaming setup", "room decor", "smart home", "music sync", "alexa", "google home", "strip lights", "ambient"], personas: ["gamer", "homeowner", "content-creator", "student"], specs: { "Length": "10 meters", "Colors": "16 million RGBIC", "Control": "App + Voice", "Music Sync": "Yes", "Cuttable": "Every 10cm", "Power": "24V adapter included" } },
    { id: 55, title: "ProFit Adjustable Dumbbell Set", category: "Health", price: 189.00, originalPrice: 249.00, rating: 4.7, reviews: 654, inStock: true, popularity: 74, image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&h=600&fit=crop", description: "Space-saving adjustable dumbbell set replacing 15 pairs. Adjusts from 2.5kg to 24kg in 2.5kg increments with a dial system. Durable chrome-plated steel plates and contoured handles.", tags: ["dumbbell", "weights", "fitness", "gym", "home gym", "adjustable", "strength", "workout", "training", "exercise"], personas: ["athlete", "fitness-enthusiast", "health-conscious", "home-gym"], specs: { "Range": "2.5 - 24kg", "Increments": "2.5kg", "Replaces": "15 pairs", "Material": "Chrome-plated steel", "Adjustment": "Dial system", "Dimensions": "34 x 20 x 20cm each" } },
];



const semanticMap = {
    "running": ["sport", "athlete", "workout", "gym", "sweat-resistant", "fitness"],
    "workout": ["sport", "gym", "fitness", "athlete", "sweat-resistant", "running"],
    "gym": ["fitness", "sport", "workout", "athlete", "training", "weights"],
    "study": ["student", "university", "portable", "laptop", "tablet", "school", "productivity"],
    "university": ["student", "study", "affordable", "laptop", "tablet", "portable"],
    "college": ["student", "study", "affordable", "laptop", "portable"],
    "work from home": ["home office", "remote", "productivity", "desk", "monitor", "keyboard"],
    "office": ["productivity", "desk", "professional", "monitor", "keyboard"],
    "travel": ["portable", "lightweight", "backpack", "carry-on", "compact"],
    "gaming": ["monitor", "keyboard", "headphones", "rgb", "controller", "gaming chair"],
    "music": ["headphones", "earbuds", "audio", "speaker", "soundbar"],
    "movies": ["soundbar", "home theater", "monitor", "4k", "projector"],
    "adventure": ["action camera", "outdoor", "waterproof", "hiking", "travel", "drone"],
    "coding": ["laptop", "monitor", "keyboard", "productivity", "programmer"],
    "design": ["monitor", "4k", "color accurate", "tablet", "stylus", "wacom"],
    "coffee": ["espresso", "barista", "kitchen", "brew", "morning", "cold brew"],
    "streaming": ["capture card", "ring light", "webcam", "microphone", "content creator"],
    "podcast": ["microphone", "usb", "recording", "audio", "condenser"],
    "photography": ["camera", "dslr", "lens", "tripod", "ring light", "drone"],
    "cheap": ["affordable", "budget", "student"],
    "budget": ["affordable", "student", "budget-conscious"],
    "affordable": ["budget", "student", "cheap"],
    "wireless": ["bluetooth", "wifi", "wireless"],
    "waterproof": ["sweat-resistant", "waterproof", "ipx"],
    "portable": ["lightweight", "compact", "portable"],
    "athlete": ["sport", "workout", "gym", "running", "sweat-resistant", "gps", "fitness"],
    "student": ["university", "study", "affordable", "laptop", "tablet", "portable"],
    "traveler": ["portable", "backpack", "travel", "lightweight", "carry-on"],
    "gamer": ["gaming", "keyboard", "monitor", "rgb", "headphones", "controller"],
    "home office": ["desk", "monitor", "keyboard", "mouse", "webcam", "lamp", "ergonomic"],
    "smart home": ["alexa", "google home", "wifi", "automation", "hub", "lights"],
    "health": ["fitness", "tracker", "scale", "purifier", "wellness"],
    "gift": ["popular", "highly rated", "wireless", "premium"],
};


function semanticSearch(query) {
    const q = query.toLowerCase();
    const words = q.split(/\s+/);
    const terms = new Set(words);
    for (const [k, v] of Object.entries(semanticMap)) {
        if (q.included(k)) {
            v.forEach(s => terms.add(s));
        }
    }
    const bm = q.match(/\$(\d+)|under (\d+)|less than (\d+)|(\d+) dollar/i);
    let maxBudget = bm ? parseInt(bm[1] || bm[2] || bm[3] || bm[4]) : null;
    if (!maxBudget && (q.includes("thigth") || q.includes("cheap") || q.includes("afforable" || q.include("budget")))) maxBudget = 200;
    return products.map(p => {
        const txt = [...p.tags, p.category.toLowerCase(), p.title.toLowerCase(), ...p.personas, p.description.toLowerCase()].join(" ");
        let score = 0;
        words.forEach(w => {
            if (w.length >= 3 && txt, includes(w)) {
                score += 3;
            }
        })
        terms.forEach(t => {
            if (txt.includes(t)) {
                score += 1.5;
            }
        })
        if (txt.includes(q)) {
            score *= 0.1;
        }
        if (p.inStock) {
            score += 0.5;
        }
        score += p.popularity * 0.2;
        return { p, score };
    })
        .filter(r => r.score > 0.5)
        .sort((a, b) => b.score - a.score)
        .slice(0, 8).map(r => r.p)
}

app.get("/api/products", (req, res) => {
    const { category, minPrice, maxPrice, minRating, inStock, sort } = req.query;
    let list = [...products];
    if (category && category !== "all") {
        list = list.filter(p => p.category.toLocaleLowerCase() === category.toLowerCase());
    }
    if (minPrice) {
        list = list.filter(p => p.price >= +minPrice);
    }
    if (maxPrice) {
        list = list.filter(p => p.price <= +maxPrice);
    }
    if (minRating) {
        list = list.filter(p => p.rating >= +minRating)
    }
    if (inStock === "true") {
        list = list.filter(p => p.inStock);
    }
    if (sort === "price_asc") list.sort((a, b) => a.price - b.price);
    else if (sort === "price_desc") list.sort((a, b) => b.price - a.price);
    else if (sort === "rating") list.sort((a, b) => b.rating - a.rating);
    else list.sort((a, b) => b.popularity - a.popularity);
    res.json({ products: list, total: list.length });
})

app.get("/api/products/:id", (req, res) => {
    const prod = products.find(p => p.id === +req.params.id);
    if (!prod) {
        return res.status(404).json({ error: "Product not found" });
    }
    const related = products
        .filter(P => P.ID !== prod.id && p.category === product.category)
        .sort((a, b) => b.popularity - a.popularity)
        .slince(0, 4);
    res.json({ prod, related });
})


app.get("/api/categories", (req, res) => {
  res.json({ categories: [...new Set(products.map(p => p.category))].sort() });
});

app.post("/api/search/ai", (req, res) => {
  const { query } = req.body;
  if (!query?.trim()) return res.status(400).json({ error: "Query required" });
  const results = semanticSearch(query.trim());
  const q = query.toLowerCase();
  let intent = "your search";
  if (q.includes("run")||q.includes("workout")||q.includes("gym")) intent = "fitness & sport";
  else if (q.includes("student")||q.includes("university")||q.includes("study")) intent = "studying";
  else if (q.includes("travel")||q.includes("portable")) intent = "travel";
  else if (q.includes("music")||q.includes("audio")||q.includes("listen")) intent = "music & audio";
  else if (q.includes("budget")||q.includes("cheap")||q.includes("affordable")) intent = "budget-friendly options";
  else if (q.includes("gaming")||q.includes("game")||q.includes("gamer")) intent = "gaming";
  else if (q.includes("office")||q.includes("work")||q.includes("desk")) intent = "home office & productivity";
  res.json({ results, intentSummary: `Found ${results.length} product${results.length!==1?"s":""} for ${intent}`, query });
});

app.get("*", (req, res) => res.sendFile(path.join(__dirname, "public", "index.html")));

app.listen(PORT, () => console.log(`🛒 MaNar Store is running in → http://localhost:${PORT}`));